stpm33: main.c gpio.c spi.c metrology.c metrology_hal_spi.c metroTask.c recordReadings.c  ../ipc/msg_queue.c
	arm-linux-gnueabihf-gcc main.c gpio.c spi.c metrology.c metrology_hal_spi.c metroTask.c recordReadings.c ../ipc/msg_queue.c -o metering.out -lsqlite3
